server:
  port: 9988

spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/upload?characterEncoding=utf-8
#    username: root
#    password: superman713
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: fordearme2018
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms
#    timeout: 2000ms
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .html


logging:
  config: classpath:logback.xml

pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    appid: 2016091900546447
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNwg4kYSVfalVzr18ZvAGv/J96rQFsED7Kr5i3qbOkljCKK28T7aqT+upzIBCEcIIcv6JV5fT+cHKLZwj5ef7VecvixYEWgBEBru0jQCAdaeOdNsVuyl1EDo0N/ZOAjSKnoQAhTR8ZPVFbT8bW6KizmaFYjzwY+yaooV4+UVT5Zf2FBE10ZJC1pWoHxHAIIL5Nl8urZSKU71P2dK5VvTUrul+ZwvaylcNPAAOJcMYJiJIJLkNj+FPQUW82b6V8TgrLROWCmhd1eiQSVnI9/f9AUhuTqoDgDNBmSnclyUxdkftfFI/fZcycUN1wi0bwC+/f8pnEF4dnhvE40GjGGjrHAgMBAAECggEABQZS4AE9hONNAhu+QDhEywsmT//f5AezYhXVUPVH89aLA+rENi2fdT1YoBoL29XtFr3IMElFZNtxg/V0APvNB54YlwIvMC/76lZb+3rjaId/VOxDFUlBAw+M+mj5mH3oM47mZUfJiWh+AMGUJ7v5dtxENtJk6/HDDgkiQQ06+NgSIUuWcg3tJtfZPmEb9zfey53NHZMewuTIHiINTeZxGmxxhKYI/4FUGp3l+y5YJzvRt9rqIOC0zK56Sz40Vs84n5f2DEQ6AjMb/H+HT6iFaeq/XkMjC2aPrOnG4N4azberFIUtkXEUHL24ibVj+Y0mPtikg3wLuE/n3GkrHeU4QQKBgQDCypzapgRicrmIuXFwVsIk2l2+C9dZsQWwdKqvd+hW/6yoqxCfTwESwUJABE27OEQB8NeO5S601cr0lQJ377FM8G9SFqwMV31/HYjn39UIojt/G375x+T0ZqbHTWgkttQaX5O9RvrZil3BazGBgClxa5vo3WWcgd6kCuyQYgz45wKBgQC6TVW8BRrzcFMhTvJQNvPsDFed8mZnzO5EFMe+SxHraUQM/YNS6913XVy4RUs6sRd+1EYtMI/pGh9xS020xBeuAY+jC5Uwpi8YtkLtTxStnYUApGprX9Sl8nm5B/0gnjRCLP0Cy7NmzWwUs0IAn0IPz9GjHKHqarZ/nfZpTMMTIQKBgEzPvsiNnL8BhF4A2lW1MHt9zGdrnfDVWGv7pW7p9qmPypL8WeKoMcEmiixaRhikmFS3lxjXEPLoN075D28iCqVPTmZtYEzBl1Av4lOlNQlhh9qYihqPE564d92xjXakzcDUnZqOyc5MvKnPzkbFthHuoB1UaIQtxhCj6iMJNxpTAoGBAJpAKboxJ+1jlRDBAtPzi+ZnGaxG5Q8QmD56Th96nG2jjJqM1Ey1yXppLLnNdco0klWKgEguKxk/bcUqKj5/FXQXCsxebLoI/nmhfqxpi59sCpFLkGkywShdKPdQa/6zvmUERsAn1HRLpS9GdGF7ewEIenRo4o7qqAvlx/3LdsDBAoGAHp0iREb9xDO56/dfCpWERVW7VCKvOzapSAlljVg8MkSjHD/amXKFrAyTG3fCl6PEZw5rm9p6VDUK9BcKrSLnC6MCizE6+lJigNRpeAX/cl86QXYWFCBwXtQ08DCAAK28cvH7/epEt7VR1f4HIvobqBN4bFThkwk7sRiTZtzPA1c=
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw/2790O/wmLFn3xPy42JeRrzmbzsQjlEp9DWR/0etHYup0t0xMdBqGJnxe2q96ax22kHypl6grx57Vugs2onCzMYskbKTsP6wKR9gx0s6osH+Dhsl6BkcuaRWEbMuwG8nfNfRFLmMyW16018K82VErgEVGfiQLhaSpqdovD9b/iSUtOsR4K4+TAELEt9IAzeExCuTNfMiCeGMOHNVOWEejDk2p3amO7R82x8sfLChvipWqQxzF0K2xBJXhq2SEFZq4J9qiZ0dxW9HLW0G5OH6tw0Lge3i5WyRvf7kq+Xy5vLisco0OZeE7/KLQ4TRUgnB910aO9N19thjW9Po0aPzQIDAQAB
    returnUrl: https://www.geekerit.com/pay/returnUrl
    notifyUrl: https://www.geekerit.com/pay/alipay/notifyUrl
    charset: UTF-8
    format: json
    signType: RSA2
    payeeUserId: 2088102176309319